# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs'
workspace 'VideoChat'
platform :ios, '9.0'

abstract_target 'TwilioVideo' do
    pod 'TwilioVideo', '~> 2.6'
    
    target 'VideoChat' do
        project 'VideoChat.xcproject'
    end
end
